### ISSUE TITLE
Duplicate entry errors in log, old statistics data is inaccessible

### ISSUE THREAD

**Issue by lmagyar** [lmagyar/homeassistant-addon-mariadb-inmemory#18]
The HA log is full of with recorder errors. Old statistics values are inaccessible, though they are in the database.

<details>
  <summary>HA log...</summary>
  
  ```
2022-11-06 09:58:24.118 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (MySQLdb.IntegrityError) (1062, "Duplicate entry '1-2022-10-27 14:00:00.000000' for key 'ix_statistics_statistic_id_start'")
[SQL: INSERT INTO statistics (created, start, mean, min, max, last_reset, state, sum, metadata_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2022, 11, 6, 8, 58, 24, 114668, tzinfo=datetime.timezone.utc), datetime.datetime(2022, 10, 27, 14, 0, tzinfo=datetime.timezone.utc), 23.599999999999998, 23.6, 23.6, None, None, None, 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-11-06 09:58:24.136 WARNING (Recorder) [homeassistant.components.recorder.statistics] Blocked attempt to insert duplicated statistic rows, please report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+recorder%22
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry '1-2022-10-27 14:00:00.000000' for key 'ix_statistics_statistic_id_start'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 101, in session_scope
    session.commit()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3429, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3568, in _flush
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3529, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (MySQLdb.IntegrityError) (1062, "Duplicate entry '1-2022-10-27 14:00:00.000000' for key 'ix_statistics_statistic_id_start'")
[SQL: INSERT INTO statistics (created, start, mean, min, max, last_reset, state, sum, metadata_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2022, 11, 6, 8, 58, 24, 114668, tzinfo=datetime.timezone.utc), datetime.datetime(2022, 10, 27, 14, 0, tzinfo=datetime.timezone.utc), 23.599999999999998, 23.6, 23.6, None, None, None, 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
  ```
</details>

This is due to the add-on reports to HA that it is started before it completes the import of the previously exported data.

During HA start the statistics component creates new entries in the `statistics_meta` table (same values than the old, but with new id-s), and tries to modify the old id-s in the `statistics` table, and this will result in a unique constraint collision due to the parallel data import.

Previously the add-on waited to the end of the import, but this caused timeout errors in the HA startup process.

Quick workaround:
```
>ha core stop
>docker kill addon_45207088_mariadb
```
**Note:** use docker kill, NOT stop. With this, the database will be reloaded with the uncorrupted values.
Then wait until the add-on starts.
```
>ha ad log 45207088_mariadb
>ha core start
```

**Comment by lmagyar** [comment]
Nothing helps, HA NEVER waits for this add-on to start, causing connection errors in core.
These add-on options has no effect on anything.
```
startup: system
timeout: 300
```
```
startup: services
timeout: 300
```

Even deleting service information from the Supervisor on add-on start doesn't help, HA starts and wants to connect before the add-on is ready.
```
bashio::services.delete "mysql";
```

**Comment by lmagyar** [comment]
Basically `docker run` returns at the early stages of s6 supervisor startup, never waits for the end of stage 2. See: https://github.com/just-containers/s6-overlay/issues/495 So HA supervisor never waits to a healthy add-on state. :(

Ugly workaround can be to import some statistics data at the beginning of add-on startup. :(
