### ISSUE TITLE
Unknown storage engine 'InnoDB'

### ISSUE THREAD

**Issue by yoxcu** [lmagyar/homeassistant-addon-mariadb-inmemory#22]
First Thanks for your work!

I encountered a problem after setting up your addon and restarting ha core.
In the logs it says "recorder cannot start".

I managed to trace the problem down to your addon using aria as default engine and recorder expects innodb (see https://www.home-assistant.io/integrations/recorder/  "The database engine must be InnoDB as MyIASM is not supported.")

Is there a specific reason of using aria? Or can i adjust ha such that it can work with aria?

Running:
Home Assistant OS 9.5  | core-2023.3.3
using all default settings as described in documentations

<details>
    <summary>Log</summary>

 Logger: homeassistant.components.recorder.core
Source: components/recorder/core.py:1289
Integration: recorder (documentation, issues)
First occurred: 21:44:10 (10 occurrences)
Last logged: 21:44:37

Error during connection setup: (MySQLdb.NotSupportedError) (1286, "Unknown storage engine 'InnoDB'") [SQL: CREATE TABLE event_data ( data_id INTEGER NOT NULL AUTO_INCREMENT, hash BIGINT, shared_data LONGTEXT, PRIMARY KEY (data_id) )ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci ] (Background on this error at: https://sqlalche.me/e/20/tw8g) (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.NotSupportedError: (1286, "Unknown storage engine 'InnoDB'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 806, in _setup_recorder
    self._setup_connection()
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1289, in _setup_connection
    Base.metadata.create_all(self.engine)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5581, in create_all
    bind._run_ddl_visitor(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3226, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2430, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 924, in visit_metadata
    self.traverse_single(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 963, in visit_table
    )._invoke_with(self.connection)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1526, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.NotSupportedError: (MySQLdb.NotSupportedError) (1286, "Unknown storage engine 'InnoDB'")
[SQL: 
CREATE TABLE event_data (
	data_id INTEGER NOT NULL AUTO_INCREMENT, 
	hash BIGINT, 
	shared_data LONGTEXT, 
	PRIMARY KEY (data_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci

]
(Background on this error at: https://sqlalche.me/e/20/tw8g)

</details>

**Comment by yoxcu** [comment]
Just noticed in general README.md you state

> This version uses tmpfs to store MariaDB databases in-memory. The default InnoDB storage engine is replaced with Aria storage engine (because InnoDB storage engine wastes a great amount of disk space, and Memory storage engine can't handle TEXT columns).

And i also did a bit more digging, seems like this commit is the origin: [Click](https://github.com/home-assistant/core/commit/1759f58fc110b6c3ad81d859d6e5716182ad29d2)
It is even stated that Aria is fine but not officially supported

**Comment by lmagyar** [comment]
Thank you for this report!

My first guess is that somehow the `ENGINE=InnoDB` got hard coded into the DB schema creation algorithm in HA core/recorder, again, and when this add-on is installed first time and HA core creates the DB from scratch, it can't create it because InnoDB is hard-coded.

I'm using this add-on with retention turned on, ie. it dumps it's database from memory to SD card on stop, and rereads it on start, so HA core/recorder never tries to create the DB schema from scratch. Sometimes I check it, whether this creation works, but not too often.

I will make some test...

**Comment by lmagyar** [comment]
Yeah, it was hard-coded 3 weeks ago. https://github.com/home-assistant/core/pull/88468 (Previously the migration got hard-coded https://github.com/home-assistant/core/issues/72883)

The only workaround is to pre-create the DB schema when the add-on is starting. It is not needed to be always up-to-date, the recorder will migrate to a newer version on startup. With an empty database it takes no time, so this won't be an issue.

They plan to force to use InnoDB, but as I understand, this will be only a repair recommendation. (fingers crossed)

I will create a new release soon...

**Comment by lmagyar** [comment]
OK, v2.5.2.2 is out.

This contains other changes, so please add some lines to the HA configuration as required in the changelog, though these are the changes:
```
recorder:
  db_max_retries: 20
  db_retry_wait: 15

logger:
  default: warning
  filters:
    homeassistant.components.recorder.core:
      - 'Error during connection setup: .MySQLdb.OperationalError. .2002'
      - 'Error during connection setup: .MySQLdb.OperationalError. .1130'
      - 'Error during connection setup: .MySQLdb.OperationalError. .1044'
```

**Comment by lmagyar** [comment]
Closing, because new add-on version prevents HA recorder to create the database on first start with the hard-coded InnoDB engine.
